### ISSUE TITLE
No License Selected

### ISSUE THREAD

**Issue by GadgetSteve** [JacoboGuijar/pdf-scraper-with-ocr#1]
This looks like a great project but without a license file it cannot be even considered for use in some contexts. 

Please consider adding a license - I would recommend PSF, MIT or Apache as many companies are not happy with using GPL or LGPL _but as the original author obviously it is up to you_. :-)

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository walks you through the simple process for common Open Source licenses.

**Comment by JacoboGuijar** [comment]
License added. Thanks for informing me about this.
